### ISSUE TITLE
robot immediately preempts navigation

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/strands_navigation#204]
Here's an example log:

```
[INFO] [WallTime: 1427364464.497568] /topological_navigation: Navigating From WayPoint3 to WayPoint25
[INFO] [WallTime: 1427364464.497881] 3 Nodes on route
[INFO] [WallTime: 1427364464.498025] From WayPoint3 do (human_aware_navigation) to WayPoint9
[INFO] [WallTime: 1427364464.542113] State machine starting in initial state 'MONITORED_NAV' with userdata: 
        ['goal', 'result']
[INFO] [WallTime: 1427364464.542371] Concurrence starting with userdata: 
        ['goal']
[INFO] [WallTime: 1427364464.543004] State machine starting in initial state 'NAVIGATION' with userdata: 
        ['goal', 'n_nav_fails']
[INFO] [WallTime: 1427364464.549995] Preempt on state machine requested!
[ INFO] [1427364464.742623555]: Got new plan
[INFO] [WallTime: 1427364464.746735] State machine terminating 'NAVIGATION':'preempted':'preempted'
[INFO] [WallTime: 1427364464.746951] Concurrent state 'NAV_SM' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1427364464.750552] Concurrence serviced preempt.
[INFO] [WallTime: 1427364464.750751] Concurrent Outcomes: {'NAV_SM': 'preempted'}
[INFO] [WallTime: 1427364464.750913] State machine terminating 'MONITORED_NAV':'preempted':'preempted'
[INFO] [WallTime: 1427364464.751082] PREEMPTED
[INFO] [WallTime: 1427364464.864589] setting parameters back
[INFO] [WallTime: 1427364464.864834] Fatal fail on Thursday, March 26 2015, at 10:07:44 hours (0/0)
[INFO] [WallTime: 1427364464.865019] Waiting for services...
[INFO] [WallTime: 1427364464.872446] Done
```

What I did: I clicked one of the errors in RViz. I saw the robot jiggle a bit for maybe 20ms. Then it stopped and gave a fatal fail (no recovery behaviours started!). When I try again it works. Could be related to #200 in the sense that it is left at some undefined state. The previous navigation, however, succeeded: 

```
[INFO] [WallTime: 1427364266.623557] State machine terminating 'NAVIGATION':'succeeded':'succeeded'
[INFO] [WallTime: 1427364266.623834] Concurrent state 'NAV_SM' returned outcome 'succeeded' on termination.
[INFO] [WallTime: 1427364266.624412] Concurrent Outcomes: {'NAV_SM': 'succeeded'}
[INFO] [WallTime: 1427364266.624617] State machine terminating 'MONITORED_NAV':'succeeded':'succeeded'
[INFO] [WallTime: 1427364266.624791] SUCCEEDED
[INFO] [WallTime: 1427364266.973130] setting parameters back
[INFO] [WallTime: 1427364266.973397] navigation finished on Thursday, March 26 2015, at 10:04:26 hours (12/5)
[INFO] [WallTime: 1427364266.973798] Waiting for services...
[INFO] [WallTime: 1427364266.978620] Done
```

**Comment by marc-hanheide** [comment]
to replicate: I just ran the [aaf_simulation](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/aaf_simulation) and send the root around using the interactive markers in rviz. Tested on two different machines (one slow, one fast), happens in both of them, say every tenth click...

**Comment by Jailander** [comment]
that is weird I didn't notice such behaviour :/ is it between two especifical nodes

**Comment by bfalacerda** [comment]
This is topological navigation cancelling the mon nav goal (note that move_base was executing as it printed out a "Got new plan"), so it doesnt try to recover, it got cancelled by the higher level.

A side note, you're not launching monitored_navigation with the config file in https://github.com/strands-project/strands_recovery_behaviours/blob/hydro-devel/strands_recovery_behaviours/config/monitored_nav_config.yaml, so you're just running the bare bone state machine (_not_  that it would make a difference in this specific case, as I said above). There should be some warnings being printed at startup.

Anther side note, the "normal" navigation will be done using the execute_policy_mode action from topological_navigation instead of the topological_navigation action (so we use the mdp planning). I don't think this is integrated in the executive yet (@hawesie?). From what I understand, we'll use the topological_navigation action for the walking group, are we using it for anything else?

**Comment by marc-hanheide** [comment]
@Jailander no it was between any nodes (maybe neighbouring, but still quite far apart).

@bfalacerda I'm a bit lost in this, I presume you mean the route will be determined by the mdp policy, but it would still use the topological graph etc? right? So for me that's still topo navigation, just not using A\* for the route planning?

**Comment by bfalacerda** [comment]
we made a new [action server](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_navigation/scripts/execute_policy_server.py)  when i was in lincoln that executes policies (i.e., state-action mappings) instead of a sequential plan. That helps with many of the bugs we had before as we now have a specialised executor for policies instead of calling topological_navigation all the time. That's the one being called by the mdp executor, and once the task executor starts using it, most of our navigation will not use the topologican_mnavigation action server

**Comment by Jailander** [comment]
yes but are we using the mdp on the deployments?

I am trying to reproduce the issue on my PC I'll try to fix it

**Comment by marc-hanheide** [comment]
OK, that was news to me... have you been testing this extensively? I mean, we are pretty close to the feature freeze. Also, will it have all the features (i.e. same topics and additional services) we had before in it? Like all the statistics, route publishing etc... and the integration with human_aware nav?

I'm a bit nervous, you know...

**Comment by bfalacerda** [comment]
yes, the navigation is tested, and we will put bob roaming around with it here today. All the other features are there, as they come from other nodes in topological_navigation (except the logging I think, which is implemented in both action servers from what I remember).

**Comment by marc-hanheide** [comment]
OK, we'll give a try...

**Comment by bfalacerda** [comment]
if you want to check it out:

```
roslaunch mdp_plan_exec mdp_plan_exec.launch topological_map:=top_map_name
```

```
rosrun actionlib axclient.py /execute_policy
```

Send goals with task type = 0. target_id is the waypoint name.

Since we don't have the statistic being used to build the mdp https://github.com/strands-project/strands_navigation/issues/189 , it is generating shortest paths in terms of number of edges to be navigated

**Comment by marc-hanheide** [comment]
Cool, thanks. @jailander reassured me that it should all be working. So I shall relax.

**Comment by Jailander** [comment]
Ok I've had a simulation running for 12 hours running policy_executor haven't seen it, I'll do the same with top_nav today and seeif I manage to find an answer for this

**Comment by bfalacerda** [comment]
has this been seen again?

**Comment by Jailander** [comment]
@marc-hanheide what @bfalacerda said
