### ISSUE TITLE
monitored_navigation.py CPU load

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#304]
When the robot is navigating I see a number of high CPU load entries in htop related to monitored navigation (see attached image). Is there anything going on in mon nav that is that CPU intensive or can a few tweaks to sleeps, rates etc. reduce the load? This could have a major effect on battery levels and robot performance long-term.

![screenshot from 2016-04-19 09 27 27](https://cloud.githubusercontent.com/assets/927289/14632716/18f0f6aa-0612-11e6-9b5a-f5e1a00273f4.png)

**Comment by bfalacerda** [comment]
it should't be this high, but i don't see anything that could do this. I assume that's when he's navigation normally. at that time we have an action client running, plus 4 concurrent monitor states which are subscribing to different topics. 2 of these topics are running at 20 Hz and the others are slower. 

It might be the smach concurrency implementation, I don't see another reason

**Comment by marc-hanheide** [comment]
we have never seen this in AAF, however, we had a number of cases where a "wait-for-topic" had been implemented, so code that waited for a topic to appear in some monitor thread that had very little sleep in it. Maybe you are using such a function somewhere?

**Comment by bfalacerda** [comment]
sorry @marc-hanheide i didn't get what you mean.

atm i'm subscribing to `/bumper`, `barrier_status`, `odom`, `cmd_vel` and `/teleop_joystick/joy
`. I subscribe in the **init** method and that's pretty much it.

**Comment by marc-hanheide** [comment]
Disclaimer: I _didn't_ look at your code

Just wanted to say two things: 
1. In the AAF setup monitored_nav does _not_ use a lot of CPU
2. In AAF we had, however, issues with code that waited for publisher to appear (e.g. localise by topic) using a lot of CPU, this was due to a stupid implementation of [`get_topic_type`](https://github.com/strands-project/strands_navigation/commit/270daf251cc67916f60b92dfc28c582b20031799#diff-e0577a4bc920b8757a69c63123bc47d0R36) in ROS's original `rostopic` module. So if you use `get_topic_type`, bear this in mind.

**Comment by bfalacerda** [comment]
OK. 2. is void in my case. one is weird though, it should be the same setup... thanks

**Comment by hawesie** [comment]
Do we get it on the robots? Maybe its just a quirk when I was running navigation in simulation?

**Comment by bfalacerda** [comment]
jsut did a couple of tests and bob looks alright, normal loads
