### ISSUE TITLE
Move topological_rviz_tools somewhere else?

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#386]
i suspect a few people want to use `topological_rviz_tools` without many of the packages int this repo. I suggest we move it to its own repo either under strands, lcas or ori-goals. Any thoughts @heuristicus @marc-hanheide ?

**Comment by heuristicus** [comment]
I think it would make sense if it lives in https://github.com/LCAS/topological_navigation, since you need those components for it to work. Although perhaps as a user interface component it would be sensible to separate it.

**Comment by Jailander** [comment]
I think that for release purposes it is a lot easier if it is hosted either in here or in [https://github.com/LCAS/topological_navigation](https://github.com/LCAS/topological_navigation),  I would argue that since the toponav repo is the one with more active maintenance maybe it makes sense to move it there.
@heuristicus if you decide for the move, it would be nice to move it with all the commit history I am happy to help you with it.

**Comment by heuristicus** [comment]
Sure, if you have any tips on moving the directory it would be useful, since I don't think I've done it before. My initial guess would be to add strands_navigation as a remote in topological_navigation, then cherry-pick all commits that happened on files in the topological_rviz_tools directory. Perhaps that's a naive approach that wouldn't work.

Something like: https://stackoverflow.com/questions/19821749/git-cherry-pick-or-merge-specific-directory-from-another-branch

**Comment by marc-hanheide** [comment]
I already wondered why @Jailander hadn't included the rviz tools into `topological_navigation`. I think that's where they should be.

**Comment by marc-hanheide** [comment]
And @heuristicus is right, that's the preferred way to keep the commit history.

**Comment by hawesie** [comment]
So, we're all for the move to `topological_navigation` in LCAS then. Excellent.

**Comment by heuristicus** [comment]
PR here: https://github.com/LCAS/topological_navigation/pull/8

**Comment by heuristicus** [comment]
PR for removal in strands_navigation at https://github.com/strands-project/strands_navigation/pull/387

**Comment by Jailander** [comment]
> I already wondered why @Jailander hadn't included the rviz tools into `topological_navigation`. I think that's where they should be.

Hi because I only moved the ones I am mostly the maintainer :sweat_smile: , but in hindsight...
