### ISSUE TITLE
How should we represent the charging point in the system?

### ISSUE THREAD

**Issue by hawesie** [strands-project/strands_navigation#48]
I can imagine two ways to encode charging point in the system.

1) The way we do it now: the node 1m away from charging point is the waypoint the robot goes to. It can then call the charging action with dock to start charging and undock to leave the station.

2) The charging point itself is a node in the topological map and can be reached from a nearby facing node by a dock transition in the topological map and left via an undock transition. 

The latter has the advantage that we can then refer to the _docking station itself_ as a location in our tasks such that tasks can be performed whilst docked. We can easily wrap the existing docking action server into separate dock and undock action servers. Therefore I prefer the second option, but as it's a change to our current way of doing things, I'm open to discussion.

**Comment by bfalacerda** [comment]
I also like 2) and I don't see it changing too much in the system. It also has the advantage of allowing the charging action to also be monitored.

**Comment by marc-hanheide** [comment]
The second option seems more consistent with the ways we operate. However, I cannot really assess all its implications, I'm afraid. But if possible, that's the way to go I'd say.

**Comment by gestom** [comment]
The second option seems better to me as well. 
I will split the charging into two servers.

**Comment by hawesie** [comment]
Excellent, thanks all, and particularly to @gestom to picking up the task :)

**Comment by bfalacerda** [comment]
@gestom , can you use MoveBaseAction like ramp and door actions, so we just need to make sure to put the right action labels in the topological map?

**Comment by gestom** [comment]
OK

**Comment by Jailander** [comment]
Sorry I'm joining late to the discussion, the way I had it in the topological patroller was the first option, the charging point was facing the charging station and from there you called the Docking server like a task associated to that waypoint, that seems to be also consistent with our framework.
In any case as I'm writing this I realise that using the second option we could launch an action server at the charging station that monitors the charging, so yes let's make the second option (since @gestom volunteered).
I just have one question how are we going to handle the goal issue fpr the charging?, right now the goal is a timeout and a command (charge/undock), but for making it work using monitored navigation we need a move base goal (Since the charging station should always be pose (0,0,0,0,0,0,0) I guess we can use that) @gestom, @BFALacerda, any thoughts? 
From this perspective option number 1 is more feasible because no changes need to be done.

**Comment by bfalacerda** [comment]
we can just send the position of the charging station as the goal, even if the docking action then ignores it. The timeout would have to be made into a parameter if we want to have access to it - that's the drawback of using move base goals for every nav action, but I think its worth itt, since we can add new continuous navigation action servers without changing code in the monitored and topological navigation action servers

**Comment by hawesie** [comment]
Option 2) was implemented and works.
